name: JS Syntax Check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Check for syntax errors in JavaScript files
      - name: Run JS Syntax Check
        run: |
          for file in $(find . -name "*.js"); do
            echo "Checking $file for syntax errors..."
            node --check "$file"
          done
